### ISSUE TITLE
Difference to Fortify?

### ISSUE THREAD

**Issue by Miosame** [zacksmash/fortify-ui#11]
Don't get me wrong, I appreciate any effort to give alternatives to jetstream - but what is exactly the difference that this package offers over just doing what the fortify readme tells you to? (besides basic blade views?) - creating some views, registering them via Fortify:: facades, ..?

Is this basically just to automate said process and if you do go through the fortify steps yourself, you get the same exact outcome? I feel many have this question trying to migrate over, so please don't see this as an attack on your efforts and work to offer alternatives, just trying to understand if one needs this if they can just do the same as the fortify readme tells.

Of course automation and even creating your own bundle via https://github.com/zacksmash/fortify-ui-preset is extremely neat to have, just trying to distinguish what exactly this does or offers over just doing it "manually", e.g. having to add 2auth functions yourself or alikes? does this implement the things (2fa, ..) that fortify mentions you'll have to do "yourself"?

Again, thanks! :tada:

**Comment by zacksmash** [comment]
Great question!

So, yes this just automates the Fortify docs, to get the basics up and running with a completely blank slate. But this package also implements Fortify's 2FA and user profile/password updating. Those two items are not documented in the Fortify README file, so having that out of the box is awesome, I think. 

So, in essentially two commands, you have everything you need, via Fortify, for authentication scaffolding.

`composer require zacksmash/fortify-ui`

`php artisan fortify-ui:install`

Done!

With the preset template, I'm hoping to build out what Laravel UI had, which was an awesome way to add your own frontend libs to Fortify, without having to worry about the underlying Fortify setup, which is what this package handles. I hope this makes sense. Any other questions are welcomed!

**Comment by Miosame** [comment]
(wow that was quite a quick reply lol)

> But this package also implements Fortify's 2FA and user profile/password updating. Those two items are not documented in the Fortify README file, so having that out of the box is awesome, I think.

I absolutely agree, it basically fills in the things that fortify tells you to implement yourself then. (without becoming jetstream with too much things)

Will definitely give this a try soon, thanks for all this work. :tada: 

Would it be maybe worth it to add to the readme to clarify exactly this question? I was at least the 20th person to ask this question across different forums and such it seems. :sweat_smile:

**Comment by zacksmash** [comment]
I live in Github all day, so I'm pretty quick on the draw, when it comes to replies! 😄 

> it basically fills in the things that fortify tells you to implement yourself then. (without becoming jetstream with too much things)

You nailed it. I suppose something like this in the README wouldn't be a bad idea, feel free to submit a PR if you have something in mind!
