### ISSUE TITLE
Can you help me to find out whats going on please?

### ISSUE THREAD

**Issue by Tivixo** [zacksmash/fortify-ui#14]
Hi,
before anything, sorry for my bad English.

First, thank you for what you created for us, then, I really would be thankful if you explain me whole story about these 3 packages you made.

I'm new at Laravel, I started learning last month and at the first of my work, Laravel 8 came and change everything by jetstream and I'm really so confused about it, so I decide use fortify directly without Jetstream for start digging in and made a test project for learning purpose.
And after some search I guessed fortify-ui maybe is best choice for me, but, honestly I don't get what are **differences between fortify-uikit & fortify-ui-preset**. I'm bad in back-end and I'm worse in front-end! (but I don't give up for learning them better.)

Can you explain the **relationships between fortify-ui, fortify-uikit & fortify-ui-preset** and help understand whole story from above please?

I need made a simple ui for fortify with Tailwind and without any js.
I read the docs, i understood the fortify-ui is the base and we use other two packages for building front-end, but I need some guide and a road map to understand to from where I should begin for make a ui for it.

I know, this is a weird issue that I made :)  but I'm kind of amateur in these stuff and I really would be happy if you tell me whole story and help me figure out where I should start for a **make a simple ui for fortify with Tailwind and NO js**.

And please consider me as a so new Laravel guy and explain me this in a simple word.

Thank you a lot.

**Comment by zacksmash** [comment]
Hey, there!

You're too kind, as I didn't really "create" much. Just some automation is all. Let me try to explain it, more clearly.

FortifyUI is an automated installation of Laravel Fortify, except it also includes all of the Blade templates you need to begin building a UI for it. It also includes a lot of the features that the Laravel Fortify documentation doesn't give any instructions for, like 2-factor authentication and user password/profile updating.

**fortify-uikit** builds on top of FortifyUI, adding in styled templates using the [UIkit framework](https://getuikit.com).

**fortify-ui-preset** is a starting point for you to build something like **fortify-uikit** and include whatever frontend frameworks and libraries you'd like.

So, the process would go something like this:

```
composer require zacksmash/fortify-ui
php artisan fortify-ui:install
php artisan migrate
```

That's all.

If you would like to use UIkit for your frontend CSS, you can install FortifyUIkit

```
composer require zacksmash/fortify-uikit
php artisan fortify-ui:uikit
```

Now, you will have the styled templates, using UIkit.

If you don't want to use UIkit, you could for the **fortify-ui-preset** repo and create your own starter and install it like this

```
composer require your-name/your-starter-kit
php artisan fortify-ui:your-starter-kit
```

**Comment by Tivixo** [comment]
HI,
Thank you for helping me my friend.

Now I understand what is going on :)

I installed fortify-ui and everything is perfect, the views are simple blade and I can change it how I want and improve my front-end skills.

I dont want UIKIT because it's so ready-for-use, but about fortify-ui-preset I have a question.

I want make Tailwind and NO-JS front-end on it, but, honestly, I dont know how it's work.
I guess you mean we should:
1- download fortify-ui-preset from your git hub
2- change it by Tailwind and make it looks good
3- upload it on packagist.org for being accessible for composer
4- installing it on our laravel project by `composer require your-name/your-starter-kit`
5- everything is OK and we have our awesome front-end on Laravel :)

Is this OK or I'm wrong?

If I'm wrong I really would be thank full if you introduce me some reference or link about it for reading to help me learn it.

Thank you a lot.

**Comment by zacksmash** [comment]
You are correct! The **fortify-ui-preset** repo is actually a template repo, so you can just visit the repo page and click the green "Use This Template" button. That will get you setup to create your own starter. You can reference the FortifyUIkit repo for some direction on how it works.
