### ISSUE TITLE
Created a preset

### ISSUE THREAD

**Issue by RoelReijn** [zacksmash/fortify-ui#15]
Hi @zacksmash 

I don't know if you're planning on maintaining a list of presets created by the community but I've created a preset based on the [Tabler](https://tabler.io) framework. It would be really nice if you could include a link to my work.

The preset is can be found [here](https://github.com/Proxeuse/fortify-tabler).

By the way, thanks for your work! It really makes starting Laravel Fortify applications way quicker and easier.

**Comment by zacksmash** [comment]
@RoelReijn 

Dude, that's awesome! I'd definitely be glad to start a list on the README for presets, like yours. Thanks for reaching out!

**Comment by mikeburrelljr** [comment]
@RoelReijn Great idea!

@zacksmash [Bulma](https://bulma.io/) preset [here](https://github.com/mikeburrelljr/fortify-bulma).

**Comment by zacksmash** [comment]
Added in the latest release. Thank you for your hard work on those presets, it's awesome to see!
