### ISSUE TITLE
validateWithBag not found in Fortify Actions

### ISSUE THREAD

**Issue by pinkbluesky** [zacksmash/fortify-ui#16]
Hi, unfortunately Fortify UI is giving me some issues. app/Actions/Fortify/UpdateUserPassword and UpdateUserProfileInformation files call validateWithBag, but for some reason intelephense (VS Code) is marking it as undefined. (see screenshot).

Not really sure why this is happening, as it doesn't seem like this is a common issue. It definitely isn't due to my other code in the project, because even when I created a fresh new Laravel project and installed Fortify UI, it was still giving me the error.

Maybe it's an issue with VS Code? On a related note, in my view files for updating user passwords, error messages {{ $errors }} aren't returned even with invalid inputs. Am I retrieving the errors correctly?

Any help appreciated!
Thanks! 
![image](https://user-images.githubusercontent.com/46383286/100170048-a7703000-2e79-11eb-9cbe-ae5fc0f01fd8.png)

**Comment by zacksmash** [comment]
I don't believe those issues are related to FortifyUI. I think you're correct in that it's an issue with VS Code/Intelephense. 

As for the `{{ $errors }}`, check out [FortifyUIkit](https://github.com/zacksmash/fortify-uikit/blob/dbc3f300d47bcffad849805d389e8d5c5d449862/stubs/resources/views/profile/update-password-form.blade.php#L20). That's how you should be handling errors in that view.
