### ISSUE TITLE
2FA & E-mail verification

### ISSUE THREAD

**Issue by HRR1337** [zacksmash/fortify-ui#22]
Hi there. 

Just trying fortify-ui on a clean Laravel installation. Got the following message when to enable 2FA:

BadMethodCallException
Call to undefined method App\Models\User::twoFactorQrCodeSvg() (View: D:\laragon\www\saas\resources\views\profile\two-factor-authentication-form.blade.php)
http://saas.test/dashboard

Edit 2: For the 2FA i had to set "use HasFactory, Notifiable, TwoFactorAuthenticatable;" in my user modal. 

Edit: To enable the verifyemail I also had to "class User extends Authenticatable implements MustVerifyEmail" <<

Can be closed. 

HRR

**Comment by gui1535** [comment]
Thank you, the same error happened here and I carried out the process in Laravel 11 and it still works

**Comment by zacksmash** [comment]
@HRR1337 @gui1535 

This is all in the readme, just FYI. In order to enable certain features you have to follow those instructions.
