### ISSUE TITLE
Safe to remove package ofter installing?

### ISSUE THREAD

**Issue by nickdekruijk** [zacksmash/fortify-ui#31]
Is it true that after running `php artisan fortify:ui` the package can be safely removed again?
Wouldn't it be better/safer to run `composer require --dev zacksmash/fortify-ui` instead?

**Comment by zacksmash** [comment]
@nickdekruijk Yeah, you can absolutely remove this after running the installation, since all it does is copy/move some files around. If you want to do it as a dev dependency, by all means. If you're going to just remove it, then it doesn't really make much of a difference.

**Comment by nickdekruijk** [comment]
Maybe suggesting to use —dev in your readme is a good idea

**Comment by zacksmash** [comment]
After testing this, it's probably not a good idea to remove the package, since it incudes Fortify as a dependency. I would just leave it, or remove it without removing dependencies.
